#+TITLE: .emacs.d
#+AUTHOR: Peter Polidoro
#+EMAIL: peterpolidoro@gmail.com

* Repository Information
  - Author :: Peter Polidoro
  - License :: BSD

  DEPRECATED Use [[.dotfiles][https://github.com/peterpolidoro/.dotfiles]] repository instead.

* Install

** Linux

*** emacs

    #+BEGIN_SRC sh

      sudo apt remove emacs
      sudo apt autoremove
      sudo add-apt-repository ppa:ubuntu-elisp/ppa
      sudo apt update
      sudo apt install emacs-snapshot

    #+END_SRC

*** fonts

    The first time you load your configuration on a new machine, you'll need to run `M-x all-the-icons-install-fonts` so that icons display correctly.

    #+BEGIN_SRC sh

      sudo apt install fonts-firacode
      sudo apt install fonts-cantarell

    #+END_SRC

*** git

    #+BEGIN_SRC sh

      sudo apt install git

    #+END_SRC

*** .emacs.d

    #+BEGIN_SRC sh

      rm -rf ~/.emacs.d
      git clone git@github.com:peterpolidoro/.emacs.d.git ~/.emacs.d

    #+END_SRC

*** terminal setup

**** vterm

     #+BEGIN_SRC sh

			 sudo apt install libvterm-dev
			 cat vterm.sh >> ~/.bashrc

     #+END_SRC

*** Language Server Protocol

**** Python

		 #+begin_src sh

			 sudo apt install python3-pip
			 pip install --user "python-language-server[all]"

		 #+end_src

*** Emacs Application Framework

		#+begin_src sh

			sudo apt install \
					 python3-pyqt5 \
					 python3-pyqt5.sip \
					 python3-dbus \
					 python3-pyqt5.qtwebengine \

		#+end_src

** Mac OS

*** emacs

    #+BEGIN_SRC sh

      brew cask install emacs

    #+END_SRC

** Windows

   You can download the latest Emacs version (27.1 at the time of this writing) for
   Windows by heading to the [[https://ftp.gnu.org/gnu/emacs/windows/emacs-27/][GNU FTP site]]. Downloading and running the [[https://ftp.gnu.org/gnu/emacs/windows/emacs-27/emacs-27.1-x86_64-installer.exe][installer
   package]] will likely be the easiest way to get started. You can also [[https://chocolatey.org/packages/Emacs][install
   Emacs via Chocolatey]] if you prefer a more automated approach.

   The location where the Emacs configuration folder lives may vary based on your
   version of Windows. If you have trouble getting this to work, check the [[https://www.gnu.org/software/emacs/manual/html_node/efaq-w32/Location-of-init-file.html#Location-of-init-file][official
   FAQ]] on the topic. If you still can't get it to work, feel free to file an issue
   and I can help investigate.

   For most modern Windows versions (Windows 7+), these steps should work:

   1. Clone this repository to a folder on your system: =git clone
      https://github.com/daviwil/emacs-from-scratch=
   2. Back up any existing Emacs configuration you may already have in your home
      directory (likely =C:\Users\yourusername\=) in the =.emacs.d= folder (you
      could try moving it to =.emacs.d-old=)
   3. Rename the directory for the clone of this repo to
      =C:\Users\yourusername\.emacs.d=.
   4. Start Emacs!

** Installing the Fira Code Font

   This configuration uses the [[https://github.com/tonsky/FiraCode][Fira Code]] font by [[https://github.com/tonsky][@tonsky]] and installation instructions can be found on [[https://github.com/tonsky/FiraCode/wiki/Installing][this wiki page]].

* Recommendations

  Here are some general recommendations on Emacs usage that you might find helpful:

** Replace CapsLock with CTRL

   Most people don't use the CapsLock key (unless you like YELLING ON THE INTERNET)
   so you can use this simple fix to replace it with the CTRL to make your Emacs
   life easier. Doing this will prevent you from having to bend your pinky down all
   day long to hit all those fabled Emacs keybindings, allowing you to keep your
   hands on the home row of the keyboard.

   Here's how to do it across all 3 major operating systems:

   *Linux*

   There are [[https://askubuntu.com/questions/33774/how-do-i-remap-the-caps-lock-and-ctrl-keys][many ways]] to accomplish this in Linux, but the easiest (and most
   repeatable) I've found is to use [[https://wiki.archlinux.org/index.php/Xmodmap][xmodmap]]. First, create a file named =.Xmodmap=
   in your home folder and populate it like so:

   #+begin_src

clear lock
clear control
keycode 66 = Control_L
add control = Control_L
add Lock = Control_R

   #+end_src

   This replaces CapsLock with control and also replaces the Ctrl key on the right
   side with CapsLock just in case you ever need to use it. Most login systems
   (GDM, KDM, etc) will load this file when you log in so you might not need to do
   anything extra for it to take effect, just log out and log back in again. If
   that doesn't seem to work, you can add this line to one of your startup files
   (=.xinitrc=, =.profile=, window manager configuration, etc):

   #+begin_src sh

     xmodmap ~/.Xmodmap

   #+end_src

   *Windows*

   On Windows you can use a simple registry file to tweak the CapsLock mapping.
   Save the following text to a file called =CapsLockHack.reg=:

   #+begin_src

REGEDIT4
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Keyboard Layout]
"Scancode Map"=hex:00,00,00,00,00,00,00,00,02,00,00,00,1d,00,3a,00,00,00,00,00

   #+end_src

   Now double-click on this file in Windows Explorer and allow Windows to apply it
   to your registry settings. After you log out of your current session and log
   back in the new key mapping should be in effect. Note that this change will
   affect *all* users on your system.

   *macOS*

   Thankfully Apple saw fit to make this a first-class option in macOS. You can
   follow the [[https://support.apple.com/guide/mac-help/change-the-behavior-of-the-modifier-keys-mchlp1011/mac][official documentation]] for your version of macOS to find the Modifier
   Keys settings and then switch Caps Lock to Control on that page.
